version: '3.8'

services:
   productservice:
     image: productcontroller:latest
     ports:
       - "8080:8080"
     networks:
       - my_network

   inventoryservice:
     image: inventorycontroller:latest
     ports:
       - "8081:8081"
     networks:
       - my_network

networks:
    my_network:
      driver: bridge




